<MyGrid>
    GridLayout:
        cols: 1
        size: root.width -200, root.height - 200
        pos: 100, 100


        GridLayout:
            cols: 2

            Button:
                text: "Sign In"

            Button:
                text: "Sign Out"


        GridLayout:
            cols: 2

            Label:
                text: "First Name: "

            TextInput:
                multiline: False

            Label:
                text: "Last Name: "

            TextInput:
                multiline: False

            Label:
                text: "Email: "

            TextInput:
                multiline: False


            Label:
                text: "School: "

            TextInput:
                multiline: False


        Button:
            text: "Submit"
            